### ISSUE TITLE
Can't parse message error when create mailbox fail.

### ISSUE THREAD

**Issue by thoangtd** [iNPUTmice/jmap#78]
I try create mailbox name "vn:Spam" which exists on server 
//  message error which server return 

```json
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Mailbox/set",
            {
                "accountId": "8a64f89eb617c9b8d0d192888ed0d7de97908e95a9f48ebac60fef71493a43a1",
                "oldState": "250288f0-b259-11ed-bf56-f5dd63373400",
                "newState": "250288f0-b259-11ed-bf56-f5dd63373400",
                "notCreated": {
                    "c0298190-81b6-11ed-b189-95eb25c143c2": {
                        "type": "invalidArguments",
                        "description": "Mailbox with name=#private:test01-ldap@*****.vn:Spam already exists.",
                        "properties": [
                            "name"
                        ]
                    }
                }
            },
            "1"
        ]
    ]
}
```
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at CreateMailboxTests.main(CreateMailboxTests.java:55)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.google.common.base.Joiner.toString(Joiner.java:491)
	at com.google.common.base.Joiner.appendTo(Joiner.java:117)
	at com.google.common.base.Joiner.appendTo(Joiner.java:169)
	at com.google.common.base.Joiner.join(Joiner.java:215)
	at com.google.common.base.Joiner.join(Joiner.java:205)
	at rs.ltt.jmap.mua.service.exception.SetException.message(SetException.java:60)
	at rs.ltt.jmap.mua.service.exception.SetException.message(SetException.java:48)
	at rs.ltt.jmap.mua.service.exception.SetException.<init>(SetException.java:36)
	at rs.ltt.jmap.mua.service.exception.SetMailboxException.<init>(SetMailboxException.java:29)
	at rs.ltt.jmap.mua.service.exception.SetMailboxException.throwIfFailed(SetMailboxException.java:39)
	at rs.ltt.jmap.mua.service.MailboxService.lambda$createMailbox$3(MailboxService.java:154)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:208)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:122)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:49)
	at rs.ltt.jmap.client.api.AbstractJmapApiClient.processResponse(AbstractJmapApiClient.java:77)
	at rs.ltt.jmap.client.api.HttpJmapApiClient$1.onSuccess(HttpJmapApiClient.java:87)
	at rs.ltt.jmap.client.api.HttpJmapApiClient$1.onSuccess(HttpJmapApiClient.java:81)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
	at rs.ltt.jmap.client.util.SettableCallFuture.set(SettableCallFuture.java:40)
	at rs.ltt.jmap.client.api.HttpJmapApiClient$2.onResponse(HttpJmapApiClient.java:140)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by iNPUTmice** [comment]
I’m going to fix this crash shortly.

However @chibenwa there seems to be a problem in James `invalidArguments` is a Method-Level error (when the entire MethodCall fails because I’m using an argument that doesn’t exists.

In this context we need an appropriate *SetError* for example `invalidProperties`

Please double check with the RFC though.
