### ISSUE TITLE
EmailSubmission/set - Error while parsing JSON Response

### ISSUE THREAD

**Issue by thoangtd** [iNPUTmice/jmap#79]
==  JAME MAIL RESPONSE  ===== 
{"sessionState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943","methodResponses":[["EmailSubmission/set",{"accountId":"3a385964b9ae6f23530d9d281783781f4901f9f0059e2fbbe38b14845dc896a4","newState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943","created":{"es0":"379d535f-3b09-4790-bb79-ec70ff4dd808"}},"0"],["Email/set",{"accountId":"3a385964b9ae6f23530d9d281783781f4901f9f0059e2fbbe38b14845dc896a4","oldState":"1a360120-be63-11ed-8bf1-e90c26b1f72d","newState":"1ab67bc0-be63-11ed-8bf1-e90c26b1f72d","updated":{"1a3034c0-be63-11ed-8bf1-e90c26b1f72d":null}},"0"]]}
========== 
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.created.
	at com.google.code.gson//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.code.gson//com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.code.gson//com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.code.gson//com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.code.gson//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.code.gson//com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.code.gson//com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.code.gson//com.google.gson.Gson.fromJson(Gson.java:1003)

**Comment by iNPUTmice** [comment]
Hi,

in JMAP the response to to set.create is a map of the of the creation id to the newly created objected (not a map of the creation id to the new id as shown in this example)

So the response needs to look something like this (I’m omitting possible other attributes of the EmailSubmission objects)

```json
"created": {
    "es0": {
        "id": "379d535f-3b09-4790-bb79-ec70ff4dd808"
    }
}
```

**Comment by chibenwa** [comment]
Fixed a long time ago on James master branch and not backported on James 3.7.x ...

On master:

```
{
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
  "methodCalls": [
     ["EmailSubmission/set", {
       "accountId": "$ACCOUNT_ID",
       "create": {
         "k1490": {
           "emailId": "${messageId.serialize}",
           "envelope": {
             "mailFrom": {"email": "${BOB.asString}"},
             "rcptTo": [{"email": "${ANDRE.asString}"}]
           }
         }
    }
  }, "c1"]]
}
```

Yields

```
{
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail", "urn:ietf:params:jmap:submission"],
  "methodCalls": [
     ["EmailSubmission/set", {
       "accountId": "$ACCOUNT_ID",
       "create": {
         "k1490": {
           "emailId": "${messageId.serialize}",
           "envelope": {
             "mailFrom": {"email": "${BOB.asString}"},
             "rcptTo": [{"email": "${ANDRE.asString}"}]
           }
         }
    }
  }, "c1"]]
}
```

@iNPUTmice  you can close this issue.

@thoangtd  please use james master branch while waiting 3.8.0 nheee
